name: minc_macae
description: Aplicativo para comunicação de professores do Minc.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  mask_text_input_formatter: ^2.9.0
  sms_autofill: ^2.3.1
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  cloud_firestore: ^4.15.9
  provider: ^6.1.2
  firebase_app_check: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  # json files directory
  assets:
    - assets/icon/
    - assets/images/      

